### PR TITLE
Fix logo and title when connected to Crab

### LINKED ISSUE #13: Adjust site content and support switch networks
- [x] There should be no space between 'Ring' and 'DAO'; it needs to be changed to 'RingDAO'.
Pasted Graphic

- [x] Delete this logo and change the content when the user selects a different chain.
image

- When choosing Darwinia: RingDAO
- When choosing Crab: CrabDAO (no logo needed, text only)
- When choosing Koi: RingDAO Test Version

### PR DESCRIPTION
**Pull request by hamidroohi92**
This PR will close #13

### CODE REVIEW

File: components/nav/navbar.tsx [hunk 1]
```diff
@@ -37,14 +37,17 @@ export const Navbar: React.FC = () => {
...
+                <Image src="/images/logo-icon.png" width="36" height="36" className="shrink-0" alt="Ring Dao" />
+                <Image src="/images/logo.png" width="100" height="36" className="shrink-0" alt="Ring Dao" />
+                {chainId === 701 && (
+                  <span className="hidden py-1 text-lg font-semibold leading-tight text-[#fff] sm:block md:text-xl">
+                    Test Version
+                  </span>
+                )}
+              </>
             )}
+            {chainId === 44 && <h2 className="text-2xl font-[700]">Crab DAO</h2>}
```
Comment (hackfisher) [inline components/nav/navbar.tsx]:
```suggestion
            {chainId === 44 && <h2 className="text-2xl font-[700]">CrabDAO</h2>}
```

File: components/nav/navbar.tsx [hunk 2]
```diff
@@ -37,14 +37,17 @@ export const Navbar: React.FC = () => {
...
-              <Image src="/images/logo-icon.png" width="36" height="36" className="shrink-0" alt="Ring Dao" />
-            )}
-            <Image src="/images/logo.png" width="100" height="36" className="shrink-0" alt="Ring Dao" />
-            {chainId === 701 && (
-              <span className="hidden py-1 text-lg font-semibold leading-tight text-[#fff] sm:block md:text-xl">
-                Test Version
-              </span>
+              <>
+                <Image src="/images/logo-icon.png" width="36" height="36" className="shrink-0" alt="Ring Dao" />
+                <Image src="/images/logo.png" width="100" height="36" className="shrink-0" alt="Ring Dao" />
```
Comment (hackfisher) [inline components/nav/navbar.tsx]:
```suggestion
                <Image src="/images/logo-icon.png" width="36" height="36" className="shrink-0" alt="RingDAO" />
                <Image src="/images/logo.png" width="100" height="36" className="shrink-0" alt="RingDAO" />
```
